// Generated by CodiumAI
const mergeSort = require('./mergeSort');
describe('mergeSort', () => {

    // sorts an array of positive integers correctly
    it('should sort an array of positive integers correctly', () => {
        const input = [5, 3, 8, 1, 2, 7];
        const expectedOutput = [1, 2, 3, 5, 7, 8];
        expect(mergeSort(input)).toEqual(expectedOutput);
    });

    // handles an empty array
    it('should return an empty array when input is empty', () => {
        const input = [];
        const expectedOutput = [];
        expect(mergeSort(input)).toEqual(expectedOutput);
    });

    // sorts an array with both positive and negative integers
    it('should sort an array with both positive and negative integers correctly', () => {
        const input = [5, -3, 8, -1, 2, -7];
        const expectedOutput = [-7, -3, -1, 2, 5, 8];
        expect(mergeSort(input)).toEqual(expectedOutput);
    });
});
