// Generated by CodiumAI
const fibonacci = require('./fibonacci')
describe('fibonacci', () => {

    // generates correct sequence for n=1
    it('should return [0] when n is 1', () => {
        const result = fibonacci(1);
        expect(result).toEqual([0]);
    });

    // handles n=0 correctly
    it('should return [] when n is 0', () => {
        const result = fibonacci(0);
        expect(result).toEqual([]);
    });

    // generates correct sequence for n=5
    it('should generate correct sequence for n=5', () => {
        const result = fibonacci(5);
        expect(result).toEqual([0, 1, 1, 2, 3]);
    });

    // generates correct sequence for n=2
    it('should return [0, 1] when n is 2', () => {
        const result = fibonacci(2);
        expect(result).toEqual([0, 1]);
    });
});
