// Generated by CodiumAI
const pyramid = require('./pyramid')
describe('pyramid', () => {

    // Function generates correct pattern for n=1
    it('should generate a single \'#\' when n is 1', () => {
        const consoleSpy = jest.spyOn(console, 'log');
        pyramid(1);
        expect(consoleSpy).toHaveBeenCalledWith('#');
        consoleSpy.mockRestore();
    });

    // Function called with n=0 should produce no output
    it('should produce no output when n is 0', () => {
        const consoleSpy = jest.spyOn(console, 'log');
        pyramid(0);
        expect(consoleSpy).not.toHaveBeenCalled();
        consoleSpy.mockRestore();
    });

    // Function generates correct pattern for n=2
    it('should generate the correct pattern for n=2', () => {
        const consoleSpy = jest.spyOn(console, 'log');
        pyramid(2);
        expect(consoleSpy).toHaveBeenCalledWith(' # ');
        expect(consoleSpy).toHaveBeenCalledWith('###');
        consoleSpy.mockRestore();
    });
});
