// Generated by CodiumAI
const spiralMatrix = require('./spiral')
describe('spiralMatrix', () => {

    // Generates a 1x1 matrix correctly
    it('should generate a 1x1 matrix correctly when n is 1', () => {
        const result = spiralMatrix(1);
        expect(result).toEqual([[1]]);
    });

    // Handles n = 0 gracefully
    it('should handle n = 0 gracefully', () => {
        const result = spiralMatrix(0);
        expect(result).toEqual([]);
    });

    // Generates a 2x2 matrix correctly
    it('should generate a 2x2 matrix correctly when n is 2', () => {
        const result = spiralMatrix(2);
        expect(result).toEqual([[1, 2], [4, 3]]);
    });

    // Generates a 3x3 matrix correctly
    it('should generate a 3x3 matrix correctly', () => {
        const result = spiralMatrix(3);
        expect(result).toEqual([[1, 2, 3], [8, 9, 4], [7, 6, 5]]);
    });

    // Numbers are in correct spiral order
    it('should generate a 3x3 matrix correctly when n is 3', () => {
        const result = spiralMatrix(3);
        expect(result).toEqual([
            [1, 2, 3],
            [8, 9, 4],
            [7, 6, 5]
        ]);
    });

    // Generates a 5x5 matrix correctly
    it('should generate a 5x5 matrix correctly', () => {
        const result = spiralMatrix(5);
        expect(result).toEqual([
            [1, 2, 3, 4, 5],
            [16, 17, 18, 19, 6],
            [15, 24, 25, 20, 7],
            [14, 23, 22, 21, 8],
            [13, 12, 11, 10, 9]
        ]);
    });
});
