// Generated by CodiumAI
const vowels = require('./vowels')
describe('vowels', () => {

    // counts vowels in a string with mixed case letters
    it('should count vowels correctly when the string has mixed case letters', () => {
        const input = 'AeIoU';
        const result = vowels(input);
        expect(result).toBe(5);
    });

    // handles an empty string
    it('should return 0 when the string is empty', () => {
        const input = '';
        const result = vowels(input);
        expect(result).toBe(0);
    });

    // counts vowels in a string with only lowercase letters
    it('should count vowels correctly when the string has only lowercase letters', () => {
        const input = 'aeiou';
        const result = vowels(input);
        expect(result).toBe(5);
    });

    // counts vowels in a string with only uppercase letters
    it('should count vowels correctly when the string has only uppercase letters', () => {
        const input = 'AEIOU';
        const result = vowels(input);
        expect(result).toBe(5);
    });

    // returns 0 for a string with no vowels
    it('should return 0 for a string with no vowels', () => {
        const input = 'xyz';
        const result = vowels(input);
        expect(result).toBe(0);
    });
});
